extension radius
extension containers
extension persistentVolumes
extension secrets

param environment string

// Secure parameters with test defaults 
#disable-next-line secure-parameter-default @secure()
param username string = 'admin'
#disable-next-line secure-parameter-default @secure()
param password string = 'c2VjcmV0cGFzc3dvcmQ='
#disable-next-line secure-parameter-default @secure()
param apiKey string = 'abc123xyz'

resource app 'Radius.Core/applications@2025-08-01-preview' = {
  name: 'containers-testapp8'
  properties: {
    environment: environment
  }
}

// Create a container that mounts the persistent volume
resource myContainer 'Radius.Compute/containers@2025-08-01-preview' = {
  name: 'myapp'
  properties: {
    environment: environment
    application: app.id
    connections: {
      data: {
        source: myPersistentVolume.id
        disableDefaultEnvVars: false
      }
      secrets: {
        source: secret.id
        disableDefaultEnvVars: false
      }
    }
    containers: {
      web: {
        image: 'mcr.microsoft.com/azuredocs/aci-helloworld'
        command: []
        args: []
        workingDir: '/usr/src/app'
        ports: {
          http: {
            containerPort: 80
            protocol: 'TCP'
          }
        }
        env: {
          CONNECTIONS_SECRET_USERNAME: {
            valueFrom: {
              secretKeyRef: {
                secretName: secret.name
                key: 'username'
              }
            }
          }
          CONNECTIONS_SECRET_APIKEY: {
            valueFrom: {
              secretKeyRef: {
                secretName: secret.name
                key: 'apikey'
              }
            }
          }
          CONNECTIONS_SECRET_PASSWORD: {
            valueFrom: {
              secretKeyRef: {
                secretName: secret.name
                key: 'password'
              }
            }
          }
        }
        volumeMounts: [
          {
            volumeName: 'data'
            mountPath: '/app/data'
          }
          {
            volumeName: 'cache'
            mountPath: '/tmp/cache'
          }
          {
            volumeName: 'secrets'
            mountPath: '/etc/secrets'
          }
        ] 
        resources: {
          requests: {
            cpu: '0.1'       
            memoryInMib: 128   
          }
          limits: {
            cpu: '0.5'
            memoryInMib: 512
          }
        }
        livenessProbe: {
          httpGet: {
            path: '/'
            port: 80
            scheme: 'http'
          }
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        }
        readinessProbe: {
          httpGet: {
            path: '/'
            port: 80
          }
          initialDelaySeconds: 5
          periodSeconds: 10
        }
      }
       init: {
        initContainer: true
        image: 'mcr.microsoft.com/azuredocs/aci-helloworld'
        command: ['sh', '-c']
        args: ['echo "Initializing..." && sleep 5']
        workingDir: '/usr/src/app'
        env: {
          INIT_MESSAGE: {
            value: 'Starting initialization'
          }
        }
        resources: {
          requests: {
            cpu: '0.1'
            memoryInMib: 64
          }
        }
      }
    }
    restartPolicy: 'Always'
    volumes: {
      data: {
        persistentVolume: {
          resourceId: myPersistentVolume.id
          accessMode: 'ReadWriteOnce'
        }
      }
      cache: {
        emptyDir: {
          medium: 'memory'
        }
      }
      secrets: {
        secretName: secret.name
      }
    }
    extensions: {
      daprSidecar: {
        appId: 'myapp'
        appPort: 80
      }
    }
    platformOptions: {
      location: 'westus'
      sku: 'Confidential'
      confidentialComputeProperties:{
        ccePolicy: 'CnBhY2thZ2UgcG9saWN5CgphcGlfdmVyc2lvbiA6PSAiMC4xMC4wIgpmcmFtZXdvcmtfdmVyc2lvbiA6PSAiMC4yLjMiCgpmcmFnbWVudHMgOj0gWwogIHsKICAgICJmZWVkIjogIm1jci5taWNyb3NvZnQuY29tL2FjaS9hY2ktY2MtaW5mcmEtZnJhZ21lbnQiLAogICAgImlzc3VlciI6ICJkaWQ6eDUwOTowOnNoYTI1NjpJX19pdUwyNW9YRVZGZFRQX2FCTHhfZVQxUlBIYkNRX0VDQlFmWVpwdDlzOjpla3U6MS4zLjYuMS40LjEuMzExLjc2LjU5LjEuMyIsCiAgICAibWluaW11bV9zdm4iOiAiNCIsCiAgICAiaW5jbHVkZXMiOiBbCiAgICAgICJjb250YWluZXJzIiwKICAgICAgImZyYWdtZW50cyIKICAgIF0sCiAgICAicGF0aCI6IG51bGwKICB9Cl0KCmNvbnRhaW5lcnMgOj0gWwogIHsKICAgICJhbGxvd19lbGV2YXRlZCI6IGZhbHNlLAogICAgImFsbG93X3N0ZGlvX2FjY2VzcyI6IHRydWUsCiAgICAiY2FwYWJpbGl0aWVzIjogewogICAgICAiYW1iaWVudCI6IFtdLAogICAgICAiYm91bmRpbmciOiBbCiAgICAgICAgIkNBUF9DSE9XTiIsCiAgICAgICAgIkNBUF9EQUNfT1ZFUlJJREUiLAogICAgICAgICJDQVBfRlNFVElEIiwKICAgICAgICAiQ0FQX0ZPV05FUiIsCiAgICAgICAgIkNBUF9NS05PRCIsCiAgICAgICAgIkNBUF9ORVRfUkFXIiwKICAgICAgICAiQ0FQX1NFVEdJRCIsCiAgICAgICAgIkNBUF9TRVRVSUQiLAogICAgICAgICJDQVBfU0VURkNBUCIsCiAgICAgICAgIkNBUF9TRVRQQ0FQIiwKICAgICAgICAiQ0FQX05FVF9CSU5EX1NFUlZJQ0UiLAogICAgICAgICJDQVBfU1lTX0NIUk9PVCIsCiAgICAgICAgIkNBUF9LSUxMIiwKICAgICAgICAiQ0FQX0FVRElUX1dSSVRFIgogICAgICBdLAogICAgICAiZWZmZWN0aXZlIjogWwogICAgICAgICJDQVBfQ0hPV04iLAogICAgICAgICJDQVBfREFDX09WRVJSSURFIiwKICAgICAgICAiQ0FQX0ZTRVRJRCIsCiAgICAgICAgIkNBUF9GT1dORVIiLAogICAgICAgICJDQVBfTUtOT0QiLAogICAgICAgICJDQVBfTkVUX1JBVyIsCiAgICAgICAgIkNBUF9TRVRHSUQiLAogICAgICAgICJDQVBfU0VUVUlEIiwKICAgICAgICAiQ0FQX1NFVEZDQVAiLAogICAgICAgICJDQVBfU0VUUENBUCIsCiAgICAgICAgIkNBUF9ORVRfQklORF9TRVJWSUNFIiwKICAgICAgICAiQ0FQX1NZU19DSFJPT1QiLAogICAgICAgICJDQVBfS0lMTCIsCiAgICAgICAgIkNBUF9BVURJVF9XUklURSIKICAgICAgXSwKICAgICAgImluaGVyaXRhYmxlIjogW10sCiAgICAgICJwZXJtaXR0ZWQiOiBbCiAgICAgICAgIkNBUF9DSE9XTiIsCiAgICAgICAgIkNBUF9EQUNfT1ZFUlJJREUiLAogICAgICAgICJDQVBfRlNFVElEIiwKICAgICAgICAiQ0FQX0ZPV05FUiIsCiAgICAgICAgIkNBUF9NS05PRCIsCiAgICAgICAgIkNBUF9ORVRfUkFXIiwKICAgICAgICAiQ0FQX1NFVEdJRCIsCiAgICAgICAgIkNBUF9TRVRVSUQiLAogICAgICAgICJDQVBfU0VURkNBUCIsCiAgICAgICAgIkNBUF9TRVRQQ0FQIiwKICAgICAgICAiQ0FQX05FVF9CSU5EX1NFUlZJQ0UiLAogICAgICAgICJDQVBfU1lTX0NIUk9PVCIsCiAgICAgICAgIkNBUF9LSUxMIiwKICAgICAgICAiQ0FQX0FVRElUX1dSSVRFIgogICAgICBdCiAgICB9LAogICAgImNvbW1hbmQiOiBbCiAgICAgICIvcGF1c2UiCiAgICBdLAogICAgImVudl9ydWxlcyI6IFsKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIlBBVEg9L3Vzci9sb2NhbC9zYmluOi91c3IvbG9jYWwvYmluOi91c3Ivc2JpbjovdXNyL2Jpbjovc2JpbjovYmluIiwKICAgICAgICAic3RyYXRlZ3kiOiAic3RyaW5nIiwKICAgICAgICAicmVxdWlyZWQiOiB0cnVlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJURVJNPXh0ZXJtIiwKICAgICAgICAic3RyYXRlZ3kiOiAic3RyaW5nIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9CiAgICBdLAogICAgImV4ZWNfcHJvY2Vzc2VzIjogW10sCiAgICAiaWQiOiBudWxsLAogICAgImxheWVycyI6IFsKICAgICAgIjE2YjUxNDA1N2EwNmFkNjY1ZjkyYzAyODYzYWNhMDc0ZmQ1OTc2Yzc1NWQyNmJmZjE2MzY1Mjk5MTY5ZTg0MTUiCiAgICBdLAogICAgIm1vdW50cyI6IFtdLAogICAgIm5hbWUiOiAicGF1c2UtY29udGFpbmVyIiwKICAgICJub19uZXdfcHJpdmlsZWdlcyI6IGZhbHNlLAogICAgInNlY2NvbXBfcHJvZmlsZV9zaGEyNTYiOiAiIiwKICAgICJzaWduYWxzIjogW10sCiAgICAidXNlciI6IHsKICAgICAgImdyb3VwX2lkbmFtZXMiOiBbCiAgICAgICAgewogICAgICAgICAgInBhdHRlcm4iOiAiIiwKICAgICAgICAgICJzdHJhdGVneSI6ICJhbnkiCiAgICAgICAgfQogICAgICBdLAogICAgICAidW1hc2siOiAiMDAyMiIsCiAgICAgICJ1c2VyX2lkbmFtZSI6IHsKICAgICAgICAicGF0dGVybiI6ICIiLAogICAgICAgICJzdHJhdGVneSI6ICJhbnkiCiAgICAgIH0KICAgIH0sCiAgICAid29ya2luZ19kaXIiOiAiLyIKICB9LAogIHsKICAgICJhbGxvd19lbGV2YXRlZCI6IGZhbHNlLAogICAgImFsbG93X3N0ZGlvX2FjY2VzcyI6IHRydWUsCiAgICAiY2FwYWJpbGl0aWVzIjogewogICAgICAiYW1iaWVudCI6IFtdLAogICAgICAiYm91bmRpbmciOiBbCiAgICAgICAgIkNBUF9BVURJVF9XUklURSIsCiAgICAgICAgIkNBUF9DSE9XTiIsCiAgICAgICAgIkNBUF9EQUNfT1ZFUlJJREUiLAogICAgICAgICJDQVBfRk9XTkVSIiwKICAgICAgICAiQ0FQX0ZTRVRJRCIsCiAgICAgICAgIkNBUF9LSUxMIiwKICAgICAgICAiQ0FQX01LTk9EIiwKICAgICAgICAiQ0FQX05FVF9CSU5EX1NFUlZJQ0UiLAogICAgICAgICJDQVBfTkVUX1JBVyIsCiAgICAgICAgIkNBUF9TRVRGQ0FQIiwKICAgICAgICAiQ0FQX1NFVEdJRCIsCiAgICAgICAgIkNBUF9TRVRQQ0FQIiwKICAgICAgICAiQ0FQX1NFVFVJRCIsCiAgICAgICAgIkNBUF9TWVNfQ0hST09UIgogICAgICBdLAogICAgICAiZWZmZWN0aXZlIjogWwogICAgICAgICJDQVBfQVVESVRfV1JJVEUiLAogICAgICAgICJDQVBfQ0hPV04iLAogICAgICAgICJDQVBfREFDX09WRVJSSURFIiwKICAgICAgICAiQ0FQX0ZPV05FUiIsCiAgICAgICAgIkNBUF9GU0VUSUQiLAogICAgICAgICJDQVBfS0lMTCIsCiAgICAgICAgIkNBUF9NS05PRCIsCiAgICAgICAgIkNBUF9ORVRfQklORF9TRVJWSUNFIiwKICAgICAgICAiQ0FQX05FVF9SQVciLAogICAgICAgICJDQVBfU0VURkNBUCIsCiAgICAgICAgIkNBUF9TRVRHSUQiLAogICAgICAgICJDQVBfU0VUUENBUCIsCiAgICAgICAgIkNBUF9TRVRVSUQiLAogICAgICAgICJDQVBfU1lTX0NIUk9PVCIKICAgICAgXSwKICAgICAgImluaGVyaXRhYmxlIjogW10sCiAgICAgICJwZXJtaXR0ZWQiOiBbCiAgICAgICAgIkNBUF9BVURJVF9XUklURSIsCiAgICAgICAgIkNBUF9DSE9XTiIsCiAgICAgICAgIkNBUF9EQUNfT1ZFUlJJREUiLAogICAgICAgICJDQVBfRk9XTkVSIiwKICAgICAgICAiQ0FQX0ZTRVRJRCIsCiAgICAgICAgIkNBUF9LSUxMIiwKICAgICAgICAiQ0FQX01LTk9EIiwKICAgICAgICAiQ0FQX05FVF9CSU5EX1NFUlZJQ0UiLAogICAgICAgICJDQVBfTkVUX1JBVyIsCiAgICAgICAgIkNBUF9TRVRGQ0FQIiwKICAgICAgICAiQ0FQX1NFVEdJRCIsCiAgICAgICAgIkNBUF9TRVRQQ0FQIiwKICAgICAgICAiQ0FQX1NFVFVJRCIsCiAgICAgICAgIkNBUF9TWVNfQ0hST09UIgogICAgICBdCiAgICB9LAogICAgImNvbW1hbmQiOiBbCiAgICAgICIvYmluL3NoIiwKICAgICAgIi1jIiwKICAgICAgIm5vZGUgL3Vzci9zcmMvYXBwL2luZGV4LmpzIgogICAgXSwKICAgICJlbnZfcnVsZXMiOiBbCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICIoP2kpKEZBQlJJQylfLis9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJBWlVSRV9DTElFTlRfSUQ9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJBWlVSRV9LRVlWQVVMVF9VUkk9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJDT05ORUNUSU9OU19TRUNSRVRfQVBJS0VZPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiQ09OTkVDVElPTlNfU0VDUkVUX1BBU1NXT1JEPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiQ09OTkVDVElPTlNfU0VDUkVUX1VTRVJOQU1FPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiQ09OTkVDVElPTl9EQVRBXy4rPS4qIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiB0cnVlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJDT05ORUNUSU9OX1NFQ1JFVFNfLis9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IHRydWUKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIkZhYnJpY1BhY2thZ2VGaWxlTmFtZT0uKyIsCiAgICAgICAgInN0cmF0ZWd5IjogInJlMiIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIkhPU1ROQU1FPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiSG9zdGVkU2VydmljZU5hbWU9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJJREVOVElUWV9BUElfVkVSU0lPTj0uKyIsCiAgICAgICAgInN0cmF0ZWd5IjogInJlMiIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIklERU5USVRZX0hFQURFUj0uKyIsCiAgICAgICAgInN0cmF0ZWd5IjogInJlMiIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIklERU5USVRZX1NFUlZFUl9USFVNQlBSSU5UPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiUEFUSD0vdXNyL2xvY2FsL3NiaW46L3Vzci9sb2NhbC9iaW46L3Vzci9zYmluOi91c3IvYmluOi9zYmluOi9iaW4iLAogICAgICAgICJzdHJhdGVneSI6ICJzdHJpbmciLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJUKEUpP01QPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiVEVSTT14dGVybSIsCiAgICAgICAgInN0cmF0ZWd5IjogInN0cmluZyIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogImF6dXJlY29udGFpbmVyaW5zdGFuY2VfcmVzdGFydGVkX2J5PS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9CiAgICBdLAogICAgImV4ZWNfcHJvY2Vzc2VzIjogW10sCiAgICAiaWQiOiAibWNyLm1pY3Jvc29mdC5jb20vYXp1cmVkb2NzL2FjaS1oZWxsb3dvcmxkIiwKICAgICJsYXllcnMiOiBbCiAgICAgICJjODcwNjIxZDkyYTA1ZmE1MjMxYjgwMzIxOGJjMzMzYjI3YTNmZTVkNGExOTRhNTBiOGE5M2M5MWU4YWUyNTI2IiwKICAgICAgIjQwOTY2YjgxZmU5NzhiMTMzNzY4MTMyMWEwZWRjYjk2ZWY2ZmM0OTgxYjExZjU4ZjQzNTJhOGEzYzA3YTc1MGIiLAogICAgICAiZTEwYmNlNWUyMjc1MTY3YTI4YmQ0MDhmNTFhY2YxOWMxM2E5MjJlOWUyMDUyMGRkODA5MDk0MzZkMzMwYzUxZCIsCiAgICAgICJmNDUzNDRiOWRjMDgxYTRkNjE4OTg2ZjRhYTM0ZjIyMTBlZTFlMTIxNTdkNjk2NTM5OTRkZGY2NjQ5MmQ4NTUwIiwKICAgICAgIjk0ZjQ0ZjI3NWI5ZTM5MmI3OTg0YzM1NjFkMmQzNmRiZWRjOTc5NmQ4N2M2NDhhMGVjNTRjODQzNmJjZmUyMjUiLAogICAgICAiNmViYmY3MTYxMWRjMjExZGM1ZjIyMTI0MTMyMTBjYTU0YTEwZDQ0ZTU1NzIwZGY1MGZiNmM5MWY3Mzk0MzQyYSIsCiAgICAgICI4YjQ4NDJmMDY5ODI4MTc1MzRhNzViY2Y3MTg2NTIxM2IwOWRmYTgzMTMyMjljMzg0ZTUyMDFkYWRiZDc1ZTI1IiwKICAgICAgIjg5YTg1YzU0NWE5N2YzMjJiNTI4ZjRiZjlhMTE5YTI5MTA3YTE4ZTNlNDQ0NTk3ZGI1Mzg0NWM4ODY0MmI4MmUiCiAgICBdLAogICAgIm1vdW50cyI6IFsKICAgICAgewogICAgICAgICJkZXN0aW5hdGlvbiI6ICIvYXBwL2RhdGEiLAogICAgICAgICJzb3VyY2UiOiAic2FuZGJveDovLy90bXAvYXRsYXMvYXp1cmVGaWxlVm9sdW1lLy4rIiwKICAgICAgICAidHlwZSI6ICJiaW5kIiwKICAgICAgICAib3B0aW9ucyI6IFsKICAgICAgICAgICJyYmluZCIsCiAgICAgICAgICAicnNoYXJlZCIsCiAgICAgICAgICAicnciCiAgICAgICAgXQogICAgICB9LAogICAgICB7CiAgICAgICAgImRlc3RpbmF0aW9uIjogIi9ldGMvcmVzb2x2LmNvbmYiLAogICAgICAgICJzb3VyY2UiOiAic2FuZGJveDovLy90bXAvYXRsYXMvcmVzb2x2Y29uZi8uKyIsCiAgICAgICAgInR5cGUiOiAiYmluZCIsCiAgICAgICAgIm9wdGlvbnMiOiBbCiAgICAgICAgICAicmJpbmQiLAogICAgICAgICAgInJzaGFyZWQiLAogICAgICAgICAgInJ3IgogICAgICAgIF0KICAgICAgfSwKICAgICAgewogICAgICAgICJkZXN0aW5hdGlvbiI6ICIvZXRjL3NlY3JldHMiLAogICAgICAgICJzb3VyY2UiOiAic2FuZGJveDovLy90bXAvYXRsYXMvc2VjcmV0c1ZvbHVtZS8uKyIsCiAgICAgICAgInR5cGUiOiAiYmluZCIsCiAgICAgICAgIm9wdGlvbnMiOiBbCiAgICAgICAgICAicmJpbmQiLAogICAgICAgICAgInJvIiwKICAgICAgICAgICJyc2hhcmVkIgogICAgICAgIF0KICAgICAgfSwKICAgICAgewogICAgICAgICJkZXN0aW5hdGlvbiI6ICIvdG1wL2NhY2hlIiwKICAgICAgICAic291cmNlIjogInNhbmRib3g6Ly8vdG1wL2F0bGFzL2VtcHR5ZGlyLy4rIiwKICAgICAgICAidHlwZSI6ICJiaW5kIiwKICAgICAgICAib3B0aW9ucyI6IFsKICAgICAgICAgICJyYmluZCIsCiAgICAgICAgICAicnNoYXJlZCIsCiAgICAgICAgICAicnciCiAgICAgICAgXQogICAgICB9CiAgICBdLAogICAgIm5hbWUiOiAibWNyLm1pY3Jvc29mdC5jb20vYXp1cmVkb2NzL2FjaS1oZWxsb3dvcmxkIiwKICAgICJub19uZXdfcHJpdmlsZWdlcyI6IGZhbHNlLAogICAgInNlY2NvbXBfcHJvZmlsZV9zaGEyNTYiOiAiIiwKICAgICJzaWduYWxzIjogW10sCiAgICAidXNlciI6IHsKICAgICAgImdyb3VwX2lkbmFtZXMiOiBbCiAgICAgICAgewogICAgICAgICAgInBhdHRlcm4iOiAiIiwKICAgICAgICAgICJzdHJhdGVneSI6ICJhbnkiCiAgICAgICAgfQogICAgICBdLAogICAgICAidW1hc2siOiAiMDAyMiIsCiAgICAgICJ1c2VyX2lkbmFtZSI6IHsKICAgICAgICAicGF0dGVybiI6ICIiLAogICAgICAgICJzdHJhdGVneSI6ICJhbnkiCiAgICAgIH0KICAgIH0sCiAgICAid29ya2luZ19kaXIiOiAiL3Vzci9zcmMvYXBwIgogIH0sCiAgewogICAgImFsbG93X2VsZXZhdGVkIjogZmFsc2UsCiAgICAiYWxsb3dfc3RkaW9fYWNjZXNzIjogdHJ1ZSwKICAgICJjYXBhYmlsaXRpZXMiOiB7CiAgICAgICJhbWJpZW50IjogW10sCiAgICAgICJib3VuZGluZyI6IFsKICAgICAgICAiQ0FQX0FVRElUX1dSSVRFIiwKICAgICAgICAiQ0FQX0NIT1dOIiwKICAgICAgICAiQ0FQX0RBQ19PVkVSUklERSIsCiAgICAgICAgIkNBUF9GT1dORVIiLAogICAgICAgICJDQVBfRlNFVElEIiwKICAgICAgICAiQ0FQX0tJTEwiLAogICAgICAgICJDQVBfTUtOT0QiLAogICAgICAgICJDQVBfTkVUX0JJTkRfU0VSVklDRSIsCiAgICAgICAgIkNBUF9ORVRfUkFXIiwKICAgICAgICAiQ0FQX1NFVEZDQVAiLAogICAgICAgICJDQVBfU0VUR0lEIiwKICAgICAgICAiQ0FQX1NFVFBDQVAiLAogICAgICAgICJDQVBfU0VUVUlEIiwKICAgICAgICAiQ0FQX1NZU19DSFJPT1QiCiAgICAgIF0sCiAgICAgICJlZmZlY3RpdmUiOiBbCiAgICAgICAgIkNBUF9BVURJVF9XUklURSIsCiAgICAgICAgIkNBUF9DSE9XTiIsCiAgICAgICAgIkNBUF9EQUNfT1ZFUlJJREUiLAogICAgICAgICJDQVBfRk9XTkVSIiwKICAgICAgICAiQ0FQX0ZTRVRJRCIsCiAgICAgICAgIkNBUF9LSUxMIiwKICAgICAgICAiQ0FQX01LTk9EIiwKICAgICAgICAiQ0FQX05FVF9CSU5EX1NFUlZJQ0UiLAogICAgICAgICJDQVBfTkVUX1JBVyIsCiAgICAgICAgIkNBUF9TRVRGQ0FQIiwKICAgICAgICAiQ0FQX1NFVEdJRCIsCiAgICAgICAgIkNBUF9TRVRQQ0FQIiwKICAgICAgICAiQ0FQX1NFVFVJRCIsCiAgICAgICAgIkNBUF9TWVNfQ0hST09UIgogICAgICBdLAogICAgICAiaW5oZXJpdGFibGUiOiBbXSwKICAgICAgInBlcm1pdHRlZCI6IFsKICAgICAgICAiQ0FQX0FVRElUX1dSSVRFIiwKICAgICAgICAiQ0FQX0NIT1dOIiwKICAgICAgICAiQ0FQX0RBQ19PVkVSUklERSIsCiAgICAgICAgIkNBUF9GT1dORVIiLAogICAgICAgICJDQVBfRlNFVElEIiwKICAgICAgICAiQ0FQX0tJTEwiLAogICAgICAgICJDQVBfTUtOT0QiLAogICAgICAgICJDQVBfTkVUX0JJTkRfU0VSVklDRSIsCiAgICAgICAgIkNBUF9ORVRfUkFXIiwKICAgICAgICAiQ0FQX1NFVEZDQVAiLAogICAgICAgICJDQVBfU0VUR0lEIiwKICAgICAgICAiQ0FQX1NFVFBDQVAiLAogICAgICAgICJDQVBfU0VUVUlEIiwKICAgICAgICAiQ0FQX1NZU19DSFJPT1QiCiAgICAgIF0KICAgIH0sCiAgICAiY29tbWFuZCI6IFsKICAgICAgInNoIiwKICAgICAgIi1jIiwKICAgICAgImVjaG8gXCJJbml0aWFsaXppbmcuLi5cIiAmJiBzbGVlcCA1IgogICAgXSwKICAgICJlbnZfcnVsZXMiOiBbCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICIoP2kpKEZBQlJJQylfLis9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJBWlVSRV9DTElFTlRfSUQ9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJBWlVSRV9LRVlWQVVMVF9VUkk9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJDT05ORUNUSU9OX0RBVEFfLis9LioiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IHRydWUKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIkNPTk5FQ1RJT05fU0VDUkVUU18uKz0uKiIsCiAgICAgICAgInN0cmF0ZWd5IjogInJlMiIsCiAgICAgICAgInJlcXVpcmVkIjogdHJ1ZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiRmFicmljUGFja2FnZUZpbGVOYW1lPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiSE9TVE5BTUU9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJIb3N0ZWRTZXJ2aWNlTmFtZT0uKyIsCiAgICAgICAgInN0cmF0ZWd5IjogInJlMiIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIklERU5USVRZX0FQSV9WRVJTSU9OPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiSURFTlRJVFlfSEVBREVSPS4rIiwKICAgICAgICAic3RyYXRlZ3kiOiAicmUyIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiSURFTlRJVFlfU0VSVkVSX1RIVU1CUFJJTlQ9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJJTklUX01FU1NBR0U9U3RhcnRpbmcgaW5pdGlhbGl6YXRpb24iLAogICAgICAgICJzdHJhdGVneSI6ICJzdHJpbmciLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJQQVRIPS91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbiIsCiAgICAgICAgInN0cmF0ZWd5IjogInN0cmluZyIsCiAgICAgICAgInJlcXVpcmVkIjogZmFsc2UKICAgICAgfSwKICAgICAgewogICAgICAgICJwYXR0ZXJuIjogIlQoRSk/TVA9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAicGF0dGVybiI6ICJURVJNPXh0ZXJtIiwKICAgICAgICAic3RyYXRlZ3kiOiAic3RyaW5nIiwKICAgICAgICAicmVxdWlyZWQiOiBmYWxzZQogICAgICB9LAogICAgICB7CiAgICAgICAgInBhdHRlcm4iOiAiYXp1cmVjb250YWluZXJpbnN0YW5jZV9yZXN0YXJ0ZWRfYnk9LisiLAogICAgICAgICJzdHJhdGVneSI6ICJyZTIiLAogICAgICAgICJyZXF1aXJlZCI6IGZhbHNlCiAgICAgIH0KICAgIF0sCiAgICAiZXhlY19wcm9jZXNzZXMiOiBbXSwKICAgICJpZCI6ICJtY3IubWljcm9zb2Z0LmNvbS9henVyZWRvY3MvYWNpLWhlbGxvd29ybGQiLAogICAgImxheWVycyI6IFsKICAgICAgImM4NzA2MjFkOTJhMDVmYTUyMzFiODAzMjE4YmMzMzNiMjdhM2ZlNWQ0YTE5NGE1MGI4YTkzYzkxZThhZTI1MjYiLAogICAgICAiNDA5NjZiODFmZTk3OGIxMzM3NjgxMzIxYTBlZGNiOTZlZjZmYzQ5ODFiMTFmNThmNDM1MmE4YTNjMDdhNzUwYiIsCiAgICAgICJlMTBiY2U1ZTIyNzUxNjdhMjhiZDQwOGY1MWFjZjE5YzEzYTkyMmU5ZTIwNTIwZGQ4MDkwOTQzNmQzMzBjNTFkIiwKICAgICAgImY0NTM0NGI5ZGMwODFhNGQ2MTg5ODZmNGFhMzRmMjIxMGVlMWUxMjE1N2Q2OTY1Mzk5NGRkZjY2NDkyZDg1NTAiLAogICAgICAiOTRmNDRmMjc1YjllMzkyYjc5ODRjMzU2MWQyZDM2ZGJlZGM5Nzk2ZDg3YzY0OGEwZWM1NGM4NDM2YmNmZTIyNSIsCiAgICAgICI2ZWJiZjcxNjExZGMyMTFkYzVmMjIxMjQxMzIxMGNhNTRhMTBkNDRlNTU3MjBkZjUwZmI2YzkxZjczOTQzNDJhIiwKICAgICAgIjhiNDg0MmYwNjk4MjgxNzUzNGE3NWJjZjcxODY1MjEzYjA5ZGZhODMxMzIyOWMzODRlNTIwMWRhZGJkNzVlMjUiLAogICAgICAiODlhODVjNTQ1YTk3ZjMyMmI1MjhmNGJmOWExMTlhMjkxMDdhMThlM2U0NDQ1OTdkYjUzODQ1Yzg4NjQyYjgyZSIKICAgIF0sCiAgICAibW91bnRzIjogWwogICAgICB7CiAgICAgICAgImRlc3RpbmF0aW9uIjogIi9ldGMvcmVzb2x2LmNvbmYiLAogICAgICAgICJzb3VyY2UiOiAic2FuZGJveDovLy90bXAvYXRsYXMvcmVzb2x2Y29uZi8uKyIsCiAgICAgICAgInR5cGUiOiAiYmluZCIsCiAgICAgICAgIm9wdGlvbnMiOiBbCiAgICAgICAgICAicmJpbmQiLAogICAgICAgICAgInJzaGFyZWQiLAogICAgICAgICAgInJ3IgogICAgICAgIF0KICAgICAgfQogICAgXSwKICAgICJuYW1lIjogIm1jci5taWNyb3NvZnQuY29tL2F6dXJlZG9jcy9hY2ktaGVsbG93b3JsZCIsCiAgICAibm9fbmV3X3ByaXZpbGVnZXMiOiBmYWxzZSwKICAgICJzZWNjb21wX3Byb2ZpbGVfc2hhMjU2IjogIiIsCiAgICAic2lnbmFscyI6IFtdLAogICAgInVzZXIiOiB7CiAgICAgICJncm91cF9pZG5hbWVzIjogWwogICAgICAgIHsKICAgICAgICAgICJwYXR0ZXJuIjogIiIsCiAgICAgICAgICAic3RyYXRlZ3kiOiAiYW55IgogICAgICAgIH0KICAgICAgXSwKICAgICAgInVtYXNrIjogIjAwMjIiLAogICAgICAidXNlcl9pZG5hbWUiOiB7CiAgICAgICAgInBhdHRlcm4iOiAiIiwKICAgICAgICAic3RyYXRlZ3kiOiAiYW55IgogICAgICB9CiAgICB9LAogICAgIndvcmtpbmdfZGlyIjogIi91c3Ivc3JjL2FwcCIKICB9Cl0KCmFsbG93X3Byb3BlcnRpZXNfYWNjZXNzIDo9IHRydWUKYWxsb3dfZHVtcF9zdGFja3MgOj0gZmFsc2UKYWxsb3dfcnVudGltZV9sb2dnaW5nIDo9IGZhbHNlCmFsbG93X2Vudmlyb25tZW50X3ZhcmlhYmxlX2Ryb3BwaW5nIDo9IHRydWUKYWxsb3dfdW5lbmNyeXB0ZWRfc2NyYXRjaCA6PSBmYWxzZQphbGxvd19jYXBhYmlsaXR5X2Ryb3BwaW5nIDo9IHRydWUKCm1vdW50X2RldmljZSA6PSBkYXRhLmZyYW1ld29yay5tb3VudF9kZXZpY2UKdW5tb3VudF9kZXZpY2UgOj0gZGF0YS5mcmFtZXdvcmsudW5tb3VudF9kZXZpY2UKbW91bnRfb3ZlcmxheSA6PSBkYXRhLmZyYW1ld29yay5tb3VudF9vdmVybGF5CnVubW91bnRfb3ZlcmxheSA6PSBkYXRhLmZyYW1ld29yay51bm1vdW50X292ZXJsYXkKY3JlYXRlX2NvbnRhaW5lciA6PSBkYXRhLmZyYW1ld29yay5jcmVhdGVfY29udGFpbmVyCmV4ZWNfaW5fY29udGFpbmVyIDo9IGRhdGEuZnJhbWV3b3JrLmV4ZWNfaW5fY29udGFpbmVyCmV4ZWNfZXh0ZXJuYWwgOj0gZGF0YS5mcmFtZXdvcmsuZXhlY19leHRlcm5hbApzaHV0ZG93bl9jb250YWluZXIgOj0gZGF0YS5mcmFtZXdvcmsuc2h1dGRvd25fY29udGFpbmVyCnNpZ25hbF9jb250YWluZXJfcHJvY2VzcyA6PSBkYXRhLmZyYW1ld29yay5zaWduYWxfY29udGFpbmVyX3Byb2Nlc3MKcGxhbjlfbW91bnQgOj0gZGF0YS5mcmFtZXdvcmsucGxhbjlfbW91bnQKcGxhbjlfdW5tb3VudCA6PSBkYXRhLmZyYW1ld29yay5wbGFuOV91bm1vdW50CmdldF9wcm9wZXJ0aWVzIDo9IGRhdGEuZnJhbWV3b3JrLmdldF9wcm9wZXJ0aWVzCmR1bXBfc3RhY2tzIDo9IGRhdGEuZnJhbWV3b3JrLmR1bXBfc3RhY2tzCnJ1bnRpbWVfbG9nZ2luZyA6PSBkYXRhLmZyYW1ld29yay5ydW50aW1lX2xvZ2dpbmcKbG9hZF9mcmFnbWVudCA6PSBkYXRhLmZyYW1ld29yay5sb2FkX2ZyYWdtZW50CnNjcmF0Y2hfbW91bnQgOj0gZGF0YS5mcmFtZXdvcmsuc2NyYXRjaF9tb3VudApzY3JhdGNoX3VubW91bnQgOj0gZGF0YS5mcmFtZXdvcmsuc2NyYXRjaF91bm1vdW50CgpyZWFzb24gOj0geyJlcnJvcnMiOiBkYXRhLmZyYW1ld29yay5lcnJvcnN9Cg=='
      } 
    }
    replicas: 1
    autoScaling: {
      maxReplicas: 3
      metrics: [
        {
          kind: 'cpu'
          target: {
            averageUtilization: 50
          }
        }
      ]
    }
  }
}

resource myPersistentVolume 'Radius.Compute/persistentVolumes@2025-08-01-preview' = {
  name: 'mypersistentvolume'
  properties: {
    environment: environment
    application: app.id
    sizeInGib: 1
  }
}

resource secret 'Radius.Security/secrets@2025-08-01-preview' = {
  name: 'app-secrets-${uniqueString(deployment().name)}'
  properties: {
    environment: environment
    application: app.id
    data: {
      username: {
        value: username
      }
      password: {
        value: password
        encoding: 'base64'
      }
      apikey: {
        value: apiKey
      }
    }
  }
}
